# -*- encoding: utf-8 -*-
"""
Flask Web App - Generated by www.AppSeed.us
AppSeed - developed by RoSoft | www.RoSoftware.ro
Licence: MIT
"""

from flask            import Flask
from flask_bootstrap  import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_pymongo    import PyMongo
from flask_login      import LoginManager
from flask_bcrypt     import Bcrypt
from flask_mail       import Mail

# load RES
from assets import Assets as assets 

app = Flask(__name__, static_url_path='/static')

#Configuration of application, see configuration.py, choose one and uncomment.
#app.config.from_object('app.configuration.ProductionConfig')
app.config.from_object('app.configuration.DevelopmentConfig')

# Expose globally the assets class
app.add_template_global(assets, 'assets')

bs   = Bootstrap   (app) #flask-bootstrap
db   = SQLAlchemy  (app) #flask-sqlalchemy
lm   = LoginManager(   ) #flask-loginmanager
bc   = Bcrypt      (app) #flask-bcrypt
mail = Mail(app)

lm.init_app(app)

from app import views, models
