# -*- encoding: utf-8 -*-
"""
Slim CMS - Generated by www.AppSeed.us in Flask
AppSeed - developed by RoSoft | www.RoSoftware.ro
Licence: MIT
"""

# Resources used 
class Assets:

    WEBSITE_NAME     = 'Now UI Dashboard'
    WEBSITE_INFO     = 'Designed by Creative-Tim.com - Coded by AppSeed.us'
    WEBSITE_KEYWORDS = 'dahboard, admin, ui, appseed'

