
   <div class="page-header page-header-small">
    <div class="page-header-image" data-parallax="true"  style="background-image: url('https://www.now-ui-kit.appseed.us/assets/img/bg6.jpg');">
    </div>
    <div class="content-center" >
     <div class="container" >
      <h1 class="title" >
       Full Stack App
      </h1>
      <p class="title" >
      Modules: Login, Register, Helpers, Clean code base
      </p>
      <div class="text-center" >
       <a target="_blank" class="btn btn-primary" href="<?php echo _assets('LINK_PRODUCT_NOW_UI_KIT') ?>" >
         Get This Full Stack App
       </a>
      </div>
     </div>
    </div>
   </div>

   <div class="section section-about-us">
    <div class="container" >
     <div class="row" >
      <div class="col-md-8 ml-auto mr-auto text-center" >
       <h2 class="title" >
        Amazing Design
       </h2>
       <h5 class="description" >
        Production-ready code, written by experts. Stop Reinventing the wheel. Use a clean code base generated by AppSeed. 
        <br />According to the National Oceanic and Atmospheric Administration, Ted, Scambos, NSIDClead scentist, puts the potentially record low maximum sea ice extent tihs year down to low ice extent in the Pacific and a late drop in ice extent in the Barents Sea.
       </h5>
      </div>
     </div>
     <div class="separator separator-primary" >
     </div>
     <div class="section-story-overview" >
      <div class="row" >
       <div class="col-md-6" >
        <div class="image-container image-left"  style="background-image: url('https://www.now-ui-kit.appseed.us/assets/img/login.jpg')">
         <p class="blockquote blockquote-primary" >
          "Over the span of the satellite record, Arctic sea ice has been declining significantly, while sea ice in the Antarctichas increased very slightly"
          <br />
          <br />
          <small >
           -NOAA
          </small>
         </p>
        </div>
        <div class="image-container"  style="background-image: url('https://www.now-ui-kit.appseed.us/assets/img/bg3.jpg')">
        </div>
       </div>
       <div class="col-md-5" >
        <div class="image-container image-right"  style="background-image: url('https://www.now-ui-kit.appseed.us/assets/img/bg1.jpg')">
        </div>
        <h3 >
         So what does the new record for the lowest level of winter ice actually mean
        </h3>
        <p >
         The Arctic Ocean freezes every winter and much of the sea-ice then thaws every summer, and that process will continue whatever happens with climate change. Even if the Arctic continues to be one of the fastest-warming regions of the world, it will always be plunged into bitterly cold polar dark every winter. And year-by-year, for all kinds of natural reasons, there&acirc;&euro;&trade;s huge variety of the state of the ice.
        </p>
        <p >
         For a start, it does not automatically follow that a record amount of ice will melt this summer. More important for determining the size of the annual thaw is the state of the weather as the midnight sun approaches and temperatures rise. But over the more than 30 years of satellite records, scientists have observed a clear pattern of decline, decade-by-decade.
        </p>
        <p >
         The Arctic Ocean freezes every winter and much of the sea-ice then thaws every summer, and that process will continue whatever happens with climate change. Even if the Arctic continues to be one of the fastest-warming regions of the world, it will always be plunged into bitterly cold polar dark every winter. And year-by-year, for all kinds of natural reasons, there&acirc;&euro;&trade;s huge variety of the state of the ice.
        </p>
       </div>
      </div>
     </div>
    </div>
   </div>

   <div class="section section-team text-center">
    <div class="container" >
     <h2 class="title" >
      Here is our team
     </h2>
     <div class="team" >
      <div class="row" >
       <div class="col-md-4" >
        <div class="team-player" >
         <img  alt="Full Stack Web App - Now Ui Kit Developer AppSeed" 
               class="rounded-circle img-fluid img-raised"  src="https://www.now-ui-kit.appseed.us/assets/img/avatar.jpg"/>
         <h4 class="title" >
          Romina Hadid
         </h4>
         <p class="category text-primary" >
          Model
         </p>
         <p class="description" >
          You can write here details about one of your team members. You can give more details about what they do. Feel free to add some
          <a href="#" >
           links
          </a>
          for people to be able to follow them outside the site.
         </p>
        </div>
       </div>
       <div class="col-md-4" >
        <div class="team-player" >
         <img  alt="Full Stack Web App - Now Ui Kit Developer" 
               alt="Thumbnail Image" class="rounded-circle img-fluid img-raised"  src="https://www.now-ui-kit.appseed.us/assets/img/ryan.jpg"/>
         <h4 class="title" >
          Ryan Tompson
         </h4>
         <p class="category text-primary" >
          Full Stack Developer
         </p>
         <p class="description" >
          Stop reinventing the wheel. Use this FREE 
          <a href="#" >
           full stack app 
          </a>
          and speed up your development. Clean code base in Php, Pyhton and Javascript
         </p>
         <a target="_blank" class="btn btn-primary" href="<?php echo _assets('LINK_PRODUCT_NOW_UI_KIT') ?>" >
            Read more
         </a>
        </div>
       </div>
       <div class="col-md-4" >
        <div class="team-player" parser_dataid="30">
         <img alt="Full Stack Web App - Now Ui Kit Developer" 
               class="rounded-circle img-fluid img-raised"  src="https://www.now-ui-kit.appseed.us/assets/img/eva.jpg"/>
         <h4 class="title" >
          Eva Jenner
         </h4>
         <p class="category text-primary" >
          Fashion
         </p>
         <p class="description" >
          You can write here details about one of your team members. You can give more details about what they do. Feel free to add some
          <a href="#" >
           links
          </a>
          for people to be able to follow them outside the site.
         </p>
        </div>
       </div>
      </div>
     </div>
    </div>
   </div>

   <div class="section section-contact-us text-center">
    <div class="container" >
     <h2 class="title" >
      Enjoy this Full Stack App?
     </h2>
     <p class="description" >
      Give us a call. We are here to help.
     </p>
     <div class="row" >
      <div class="col-lg-6 text-center col-md-8 ml-auto mr-auto" >
       <div class="input-group input-lg" >
        <div class="input-group-prepend" >
         <span class="input-group-text" >
          <i class="now-ui-icons users_circle-08" >
          </i>
         </span>
        </div>
        <input class="form-control"  placeholder="First Name..." type="text"/>
       </div>
       <div class="input-group input-lg" >
        <div class="input-group-prepend" >
         <span class="input-group-text" >
          <i class="now-ui-icons ui-1_email-85" >
          </i>
         </span>
        </div>
        <input class="form-control"  placeholder="Email..." type="text"/>
       </div>
       <div class="textarea-container" >
        <textarea class="form-control" cols="80" name="name"  placeholder="Type a message..." rows="4"></textarea>
       </div>
       <div class="send-button" >
        <a class="btn btn-primary btn-round btn-block btn-lg" href="#pablo" >
         Send Message
        </a>
       </div>
      </div>
     </div>
    </div>
   </div>
   