# -*- encoding: utf-8 -*-
"""
Slim CMS - Generated by www.AppSeed.us in Flask
AppSeed - developed by RoSoft | www.RoSoftware.ro
Licence: MIT
"""

# Resources used 
class Assets:

    BRAND_NAME       = 'AppSeed'
    BRAND_INFO       = 'Automation tools & coded apps in Php, Python and Javascript'  
    HEADER_TITLE     = 'AppSeed - Automation tools & coded apps in Php, Python and Javascript' 
    HEADER_SUB_TITLE = 'Web development automation tools: Vue.js, React, Laravel, Flask, CodeIgniter, Django, Node.js' 
    HEADER_KEYWORDS  = 'automation, development tools, automatic theme parser, laravel, code igniter, flask, django, react, angular'

    SECTION_TOP_TITLE_1 = '#Automation tools'
    SECTION_TOP_TITLE_2 = 'Coded apps in Php, Python and Javascript' 

    #SECTION_TOP_TITLE_1 = 'Publish your website today'
    #SECTION_TOP_TITLE_2 = 'Choose a theme.   Push an order.   Your web application is ready! '

    SECTION_INFO_TITLE       = 'Automation tools - How it helps:'
    
    SECTION_INFO_CELL1_TITLE = 'Automatic HTML theme processing'
    SECTION_INFO_CELL1_INFO  = 'Complete assets extraction from your awesome theme: JS, CSS files, header, footer<br/> PLUS all theme components ready to be used in Vue.js, Flask, Laravel or React.'

    SECTION_INFO_CELL2_TITLE = 'Production ready Backend'
    SECTION_INFO_CELL2_INFO  = 'AppSeed will setup all basic modules: <br/> authentication, registration ORM, RECAPTCHA and cool helpers in your preffered framework: Vue.js, React, Flask or Laravel.'

    SECTION_INFO_CELL3_TITLE = 'Automated Deployment'
    SECTION_INFO_CELL3_INFO  = 'AppSeed automate and fully assist your deployment. <br/> No worries! <br/> Just focus on your product and features.'  

    #Prices
    PRICE_BASIC_PACKAGE             = '99'
    PRICE_BASIC_PACKAGE_FULL_PRICE  = '149'

    PRICE_THEME_PACKAGE             = '149'
    PRICE_THEME_PACKAGE_FULL_PRICE  = '199'

    PRICE_PREMIUM_PACKAGE            = '199'
    PRICE_PREMIUM_PACKAGE_FULL_PRICE = '249'

    PRICE_THEME_PARSING              = '99'
    PRICE_DEPLOYMENT                 = '99'

    HOME_YOUTUBE_VIDEO               = 'https://www.youtube.com/watch?v=yQmGX1RT6rU' 

