# -*- encoding: utf-8 -*-
"""
Flask Web App - Generated by www.AppSeed.us
AppSeed - developed by RoSoft | www.RoSoftware.ro
Licence: MIT
"""

from models import User
from app import app, lm, db, bc
from sqlalchemy import desc,or_

import      datetime,time,os,re

def user_exists( email, username ):

    if email and User.query.filter_by(email=email).scalar():
        return True

    if username and User.query.filter_by(user=username).scalar():
        return True 
    
def create_user( email, username, password):

    if User.query.filter_by(user=username).scalar():
        #print "Username already registerred .."
        return None

    if User.query.filter_by(email=email).scalar():
        #print "eMail already registerred .."
        return None

    # regex to check for e-mail syntax
    if not re.match("(^.+@{1}.+\.{1}.+)", str(email)):
        
        print "Invalid e-mail. Please try again."
        return None
        #return "Invalid e-mail. Please try again."

    # hash the password here (bcrypt has salting included)
    pw_hash = bc.generate_password_hash(password)

    # if form is valid and all verification is complete
    # create User object and give the parameters in order
    user = User(username, pw_hash, email)

    user.save()

    print "user created id = " + str( user.id ) 
    return user 
