# -*- encoding: utf-8 -*-
"""
Flask Web App - Generated by www.AppSeed.us
AppSeed - developed by RoSoft | www.RoSoftware.ro
Licence: MIT
"""

from flask_wtf          import Form, RecaptchaField
from flask_wtf.file     import FileField, FileRequired
from wtforms            import StringField, TextAreaField, SubmitField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

# Registration form
class RegisterForm(Form):
	email         = StringField   (u'E-mail adress'   , validators=[DataRequired()] )
	username      = StringField   (u'Username'        , validators=[DataRequired()] )
	password      = PasswordField (u'Passowrd'        , validators=[DataRequired()] )
	password_conf = PasswordField (u'Confirm password', validators=[DataRequired()] )

# Login form
class LoginForm(Form):
	username    = StringField  (u'username' , validators=[DataRequired()])
	password    = PasswordField(u'password' , validators=[DataRequired()])
